apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: axsis
build:
  local:
    push: true
  artifacts:
  - image: ingvord/axsis
    context: axsis-xes
    docker:
      dockerfile: docker/flask/Dockerfile
  - image: ingvord/axsis-magix
    context: axsis-xes
    docker:
      dockerfile: docker/magix/Dockerfile
  - image: ingvord/axsis-gui
    context: axsis-xes-gui
    docker:
      dockerfile: Dockerfile
      buildArgs:
        NODE_AUTH_TOKEN: "{{ .NODE_AUTH_TOKEN}}"
#  - image: ingvord/axsis-virtual-tango-host
#    context: axsis-virtual-tango-host
#    docker:
#      dockerfile: Dockerfile
  - image: ingvord/magix
    context: magix-war-plugin
    jib: 
      project: com.github.waltz-controls:magix
  - image: ingvord/axsis-tango-server
    context: axsis-tango-server
    jib:
      project: com.github.ingvord.axsis:AxsisTangoServer
deploy:
  kubeContext: "microk8s"
  kubectl:
    manifests:
    - axsis-kube/magix.service.yaml
    - axsis-kube/magix.yaml
    - axsis-kube/axsis.magix.yaml
    - axsis-kube/axsis.service.yaml
    - axsis-kube/axsis.yaml
    - axsis-kube/ingress.yml
#    - axsis-kube/pi-controller.external.yaml
    - axsis-kube/web.service.yaml
    - axsis-kube/web.yaml
    - axsis-kube/tango-host.yaml
    - axsis-kube/tango-server.yaml
